name: Docker Build from Rust Workspace

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch (optional)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Render Dockerfile from template for Linux target
        run: |
          TARGET=x86_64-unknown-linux-gnu
          mkdir -p scratch/shared/infra/docker_build
          sed "s/\\$\\{TARGET\\}/$TARGET/g" scratch/shared/infra/docker/templates/Dockerfile.template > scratch/shared/infra/docker_build/Dockerfile

      - name: Docker login (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_PASSWORD != '' }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Docker image for Linux target
        run: |
          docker build \
            --build-arg TARGET=x86_64-unknown-linux-gnu \
            -f scratch/shared/infra/docker_build/Dockerfile \
            scratch/shared -t doom/rust-workspace-desktop:dev-linux

      - name: (Optional) Push Docker image
        if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_PASSWORD != '' }}
        run: |
          docker push doom/rust-workspace-desktop:dev-linux
